### PR TITLE
Update to sponsor

### PR DESCRIPTION
**Pull request by villanuevawill**
.

### CODE REVIEW

**Comment by adietrichs** [comment]
Are we sure transaction syncing between peers works otherwise? If not, it might make sense to have this be part of a future "make peer transaction syncing AA compatible" PR.

**Comment by villanuevawill** [comment]
It should definitely work at this point, yes.

**Comment by adietrichs** [comment]
I think I was just a bit confused about the context of the change. Lgtm.

**Review by adietrichs — APPROVED** [review]

**Comment by villanuevawill** [comment]
image

**Pull request merged**
