### PR TITLE
EIP-1559

### PR DESCRIPTION
**Pull request by lightclient**
Rebased @i-norden's changes onto the lastest from `go-ethereum`. A few notable changes:

* Removed the custom `EIP1559Config` struct from the `ChainConfig`. It was causing some issues when reading from disk.
* Reverted the `NewTransaction` functions to not support EIP-1559, but instead introduce a new EIP-1559 specific function to make txs. This avoids ~200 extra lines in the diff.
* Updated the gas price oracle mechanism to the newly introduced architecture.

### CODE REVIEW

**Comment by i-norden** [comment]
I think it could be helpful to retain some of the original commit history, rather than having that +7,728 -1,361 diff in a single commit. Mostly a matter of preference I suppose, but I think it would beneficial for the devs we are onboarding.

**Comment by lightclient** [comment]
@i-norden in an ideal world, yes, but I found the rebase to be rather quite complicated without squashing.

**Comment by lightclient** [comment]
You can see my attempt here: https://github.com/quilt/go-ethereum/pull/30
This rebase went much more smoothly and I am more comfortable with its accuracy.

**Comment by i-norden** [comment]
That makes sense!

**Comment by lightclient** [comment]
@i-norden it turns out I was working off of https://github.com/vulcanize/go-ethereum-EIP1559/tree/eip1559_rebase instead of https://github.com/vulcanize/go-ethereum/tree/1559_test, so it looks like this work will need to be discarded anyways.

**Pull request closed without merging**
